### PR TITLE
Use open drain outputs for keyboard interface

### PR DESCRIPTION
**Pull request by rfuest**
First of all let me thank you for publishing this project. I was about to implement something similar when I discovered your repository. So far I've only tested the keyboard interface, because I haven't build a PCB yet. I haven't thoroughly tested each key, but it even seems to work with a German keyboard layout.

This PR changes the way the keyboard pins are driven by the RP2040. The current code actively drives the outputs high instead of relying on the external pullup resistors. This could be problematic if the Amiga tries to drive one of the lines low while the RP2040 drives it high, e.g. if the communication becomes unsynced and the Amiga sends the acknowledge at the wrong time. In this case the outputs would be shorted through the MOSFET body diode which could, in the worst case, damage the CIA.

### CODE REVIEW

**Comment by borb** [comment]
Hello and thank you for the PR :heart: - I've had a brief look and it looks perfect (having to do everything in short bursts as I'm recovering from spending most of the week ill with COVID).

I've literally done exactly what you've suggested here with the mouse interface because of the same concern, so this was on my radar (see [this commit](https://github.com/borb/amigahid-pico/commit/9da4bd05478d9e8d2f07de03d1ca99fde37d9b9c)) and was intending to make the same change for the keyboard interface.

I will review and accept the request very shortly!

p.s. I could really do with some thorough testing for non-US and non-UK keymaps (UK keymap has issues with two missing mapped keys which I am seeking to resolve today). If you would be happy to do so, a full test of the complete mapping would be very handy.

**Comment by borb** [comment]
> First of all let me thank you for publishing this project. I was about to implement something similar when I discovered your repository. So far I've only tested the keyboard interface, because I haven't build a PCB yet. I haven't thoroughly tested each key, but it even seems to work with a German keyboard layout.

Might be worth holding off building a PCB; I've just literally uploaded the revision 4 PCB layout which fixes the incorrect IDC to D-Sub layout mistake I made with the revision 4 PCB. I'll put an archive of the gerber files on once I've had a successful test board produced.

**Comment by rfuest** [comment]
> p.s. I could really do with some thorough testing for non-US and non-UK keymaps (UK keymap has issues with two missing mapped keys which I am seeking to resolve today). If you would be happy to do so, a full test of the complete mapping would be very handy.

Yes, I can do that for the German keymap. Can you recommend a tool on the Amiga to test the keyboard?

> Might be worth holding off building a PCB; I've just literally uploaded the revision 4 PCB layout which fixes the incorrect IDC to D-Sub layout mistake I made with the revision 4 PCB. I'll put an archive of the gerber files on once I've had a successful test board produced.

I was holding of on ordering PCBs because of the issues mentioned in the README. The new KiCad files seem to be a great improvement over the old version.

Did you already order your PCBs? I've noticed that there is a via in the keepout zone under `TP4` which could ground the test point.

**Comment by borb** [comment]
> > If you would be happy to do so, a full test of the complete mapping would be very handy.
> Yes, I can do that for the German keymap. Can you recommend a tool on the Amiga to test the keyboard?

Amiga TestKit by Keir Fraser is my go-to for picking up scan codes quickly, though for the most part it should be simple enough to do myself by looking at the keyboard layout and the rows/columns, working out the additional keys not present in other layouts. The UK layout has two additional keys which I need to work out (I attempted to guess them earlier this week, unsuccessfully, and will need to resort to TestKit, though the rev 8 A500 also had additional keys which need discovery also).

> Did you already order your PCBs? I've noticed that there is a via in the keepout zone under `TP4` which could ground the test point.

I have placed an order but it is purely for testing purposes right now - I have ordered a test to see if I can avoid using the more expensive castellated edges (as in GBP 2.60 vs GBP 32.60 for castellated edges) approach to reaching the USB D+/- pads, but if it fails I will likely need to either use a very wide via to sink through or something like pogo pins.

The USB test pads may require a kapton tape mask to prevent solder flowing into the shield anchorage point and if this is the case, then it may be needed to shield the ground via. JLC's vias are usually well coated under solder mask so I am confident that it will be okay but I strongly suspect that I will be producing another revision next weekend, at which point I will clear the keepout area again.

Again, this is mostly a test but it could prove useful.

If TI level shifting bus transceivers come back in to regular supply soon, that may be another version to produce.

**Comment by rfuest** [comment]
> Amiga TestKit by Keir Fraser is my go-to for picking up scan codes quickly, though for the most part it should be simple enough to do myself by looking at the keyboard layout and the rows/columns, working out the additional keys not present in other layouts. The UK layout has two additional keys which I need to work out (I attempted to guess them earlier this week, unsuccessfully, and will need to resort to TestKit, though the rev 8 A500 also had additional keys which need discovery also).

I'll take a look at this when I have some time. The two additional keys are also present on the German keyboard layout.

> I have placed an order but it is purely for testing purposes right now - I have ordered a test to see if I can avoid using the more expensive castellated edges (as in GBP 2.60 vs GBP 32.60 for castellated edges) approach to reaching the USB D+/- pads, but if it fails I will likely need to either use a very wide via to sink through or something like pogo pins.
> 
> The USB test pads may require a kapton tape mask to prevent solder flowing into the shield anchorage point and if this is the case, then it may be needed to shield the ground via. JLC's vias are usually well coated under solder mask so I am confident that it will be okay but I strongly suspect that I will be producing another revision next weekend, at which point I will clear the keepout area again.
> 
> Again, this is mostly a test but it could prove useful.

It was just something I noticed when looking at the layout and it is no big problem for a prototype. Can you report back if JLC accepted your order without additional cost? I would like to order a few PCBs to try the mouse support, even if there might still be some issues.

> If TI level shifting bus transceivers come back in to regular supply soon, that may be another version to produce.

Nexperia has a pin compatible IC of the TXS0108E, which is called NXS0108. Its supply isn't any better, but maybe it can be an alternative in the future.

**Comment by borb** [comment]
Many thanks; this has been merged. As a nice bonus, live reprogramming the pico via swd no longer reboots the computer so I can carry on where I left off. Useful!

**Comment by borb** [comment]
> I'll take a look at this when I have some time. The two additional keys are also present on the German keyboard layout.

It turns out I was mostly already there with my guesswork, but I'd misremembered the layout somewhat. So the return-key cutout deadkey is working correctly (code $2b), but the left shift cutout deadkey ($30) has not yet been implemented. In the USB UK layout keyboards, I'm mapping HID $64 to Amiga $0d, which is typically where deadkey $30 is, but the UK HID layout is `\|`, which is also Amiga $0d. At present, I'm missing nothing from the A500 US or UK layouts.

> It was just something I noticed when looking at the layout and it is no big problem for a prototype. Can you report back if JLC accepted your order without additional cost? I would like to order a few PCBs to try the mouse support, even if there might still be some issues.

They have accepted the order just fine without additional cost but the concern comes at production time as to whether the via is ripped out during the edge preparation. I hope it isn't but you never know.

I will report back as to the outcome of this production run. I'd really like to include a proper USB Type A socket onboard as adapters just add to wiring clutter.

> > If TI level shifting bus transceivers come back in to regular supply soon, that may be another version to produce.

> Nexperia has a pin compatible IC of the TXS0108E, which is called NXS0108. Its supply isn't any better, but maybe it can be an alternative in the future.

I was thinking more along the lines of the SN74CBTD16211 as it's 24-channel, but I haven't prototyped anything yet since I can't get hold of a TSSOP-56 package. The TVSOP-56 is available but I've never soldered that small before and I'm not working with hot hair, which makes things difficult.

The issue I had with the TXS0108E is that because of Amiga-side load drain on the reset line, pulling clk/dat low either together or alternately meant the voltage level on reset dropped - not to 0V, but low enough that the Amiga would suddenly and unexpectedly reset. I'm prepared to give it another chance if there's a workable solution to this, but it became impractical in earlier tests so I, at the time temporarily, switch to the mosfet design and have stuck with it for now. If I can prototype up a working solution I'd gladly move back to ICs because hand soldering 17 fets and 34 resistors is prone to errors for me. Hotplate or heatgun being considered in the near future!

**Comment by rfuest** [comment]
> I was thinking more along the lines of the SN74CBTD16211 as it's 24-channel, but I haven't prototyped anything yet since I can't get hold of a TSSOP-56 package. The TVSOP-56 is available but I've never soldered that small before and I'm not working with hot hair, which makes things difficult.

0.4mm pitch doesn't sound like fun if you need to solder it by hand. Is there a lower channel count version you could use for the prototype? Splitting the translation up into multiple ICs could also make the layout easier.

> The issue I had with the TXS0108E is that because of Amiga-side load drain on the reset line, pulling clk/dat low either together or alternately meant the voltage level on reset dropped - not to 0V, but low enough that the Amiga would suddenly and unexpectedly reset. I'm prepared to give it another chance if there's a workable solution to this, but it became impractical in earlier tests so I, at the time temporarily, switch to the mosfet design and have stuck with it for now.

Is the schematic and layout of rev 1 in this commit https://github.com/borb/amigahid-pico/commit/c282c32678ffb0917bdd09118bf3984637dfa28f the latest TXS0108E based version you tried? Because the +3V3 and +5V are connected to the TXS0108E via capacitors instead of a direct connection to the rails. But even without this error the layout could have caused some of your issues, because the thin power traces and fast transients from the one-shot accelerator could cause interference.

> If I can prototype up a working solution I'd gladly move back to ICs because hand soldering 17 fets and 34 resistors is prone to errors for me. Hotplate or heatgun being considered in the near future!

I would also appreciate not having to solder lots of tiny parts, because I also plan to populate the PCBs by hand. You might get away with only populating the FETs and enabling the internal pullup resistors. But that would probably have some negative impact on the signal edges.

**Comment by borb** [comment]
> Is the schematic and layout of rev 1 in this commit https://github.com/borb/amigahid-pico/commit/c282c32678ffb0917bdd09118bf3984637dfa28f the latest TXS0108E based version you tried? Because the +3V3 and +5V are connected to the TXS0108E via capacitors instead of a direct connection to the rails. But even without this error the layout could have caused some of your issues, because the thin power traces and fast transients from the one-shot accelerator could cause interference.

Yes, that's the design in question, though that decision to connect through the capacitors was wrong; the caps were supposed to be bypass from V<sub>CCA</sub> and V<sub>CCB</sub> to ground. That layout was entirely wrong from the start 😆

I had prototyped everything up on breadboard (with ground bypass, not powering through the caps) but it plainly kept on rebooting the Amiga - a key shot would pull /RES from 5V to 3.3V which ended up in reboot. Mouse motion also. I will give it another shot (possibly today) and see if some of the recent changes (particularly the open drain stuff) fix things somewhat in that respect. JLCPCB just dispatched this weekend's boards so once I can work out if this method of connecting to USB pads is feasible, if this works out, I'll put the TXS0108 ICs back in and go back to that method before having the next batch produced. Just a shame it has to be done in batches of 5 :smile:

**Comment by borb** [comment]
As per the comment on issue #7, the board run was successful. The solder mask covered the via just fine but I will move the ground plane via so it's not in the keepout area.

The via plating was knocked about a bit during drilling but survived, and the USB socket is working fine. It's a shame kicad can't do something which doesn't involve a full circular through-hole but it worked out this time. Will consult a few other people to see if there's something I can do.

Furthermore, I didn't tick the castellated edges box, and the order was accepted without additional cost, and was produced at a usable standard. I did have to cut some of the copper plating with a scalpel to tidy it up but the connection was fine.

**Comment by rfuest** [comment]
> It's a shame kicad can't do something which doesn't involve a full circular through-hole but it worked out this time.

I don't think that is true, you can add plated ovals to footprints.

**Pull request merged**
